import type { Level } from './types'

const commonHints = [
  'Run once, then use Step to watch exactly where the pointer moves.',
  'The goal checker looks at the program behavior, not just the block names.',
]

export const levels: Level[] = [
  {
    id: 1,
    title: 'Read One Cell',
    concept: 'Arrays store values at numbered positions called indexes.',
    prompt: 'Read index 2 so you can see how array access works.',
    array: [4, 9, 13, 21],
    target: 13,
    allowedBlocks: ['dsa_read_index'],
    starterBlocks: ['readIndex'],
    hints: ['Indexes start at 0, so index 2 is the third cell.', ...commonHints],
    goal: (state) => state.lastRead === 13,
    success: 'Nice. You read the third cell with array[2].',
  },
  {
    id: 2,
    title: 'Move a Pointer',
    concept: 'A pointer is a named marker for the cell your algorithm cares about.',
    prompt: 'Move the current pointer to the target value.',
    array: [5, 8, 12, 20],
    target: 12,
    allowedBlocks: ['dsa_set_pointer'],
    starterBlocks: ['setPointer'],
    hints: ['The target value 12 is at index 2.', ...commonHints],
    goal: (state) => state.pointers.current === 2,
    success: 'The current pointer is sitting on the target.',
  },
  {
    id: 3,
    title: 'Compare a Cell',
    concept: 'Search begins by comparing a candidate cell with the target.',
    prompt: 'Compare the target cell with the target value.',
    array: [7, 11, 18, 25],
    target: 18,
    allowedBlocks: ['dsa_compare_index'],
    starterBlocks: ['compareIndex'],
    hints: ['Compare index 2 with the target.', ...commonHints],
    goal: (_state, frames) => frames.some((frame) => frame.event.kind === 'compare' && frame.event.match),
    success: 'That comparison matched the target.',
  },
  {
    id: 4,
    title: 'Build Linear Search',
    concept: 'Linear search checks each item from left to right until it finds the target.',
    prompt: 'Use a loop, comparison, if block, and found output to find the target.',
    array: [3, 10, 14, 19, 26],
    target: 19,
    allowedBlocks: [
      'dsa_scan_array',
      'dsa_compare_index',
      'dsa_if_current_equals_target',
      'dsa_output_found_current',
      'dsa_output_not_found',
      'dsa_linear_search',
    ],
    starterBlocks: ['linearSearchParts'],
    hints: [
      'Inside the loop: compare current, then if it matches, output found.',
      'A single Linear Search block also works, but the loop version teaches more.',
      ...commonHints,
    ],
    goal: (state) => state.resultIndex === 3,
    success: 'Linear search found the value after checking cells from left to right.',
  },
  {
    id: 5,
    title: 'Feel O(n)',
    concept: 'O(n) means the work grows with the number of items.',
    prompt: 'Run linear search for a missing value and notice it checks every cell.',
    array: [2, 6, 9, 12, 15, 18],
    target: 99,
    allowedBlocks: ['dsa_linear_search', 'dsa_scan_array', 'dsa_compare_index', 'dsa_output_not_found'],
    starterBlocks: ['linearSearch'],
    hints: ['Because 99 is missing, linear search must inspect all 6 cells.', ...commonHints],
    goal: (state) => state.resultIndex === -1 && state.operationCount === 6,
    success: 'Exactly. Missing targets expose why linear search is O(n).',
  },
  {
    id: 6,
    title: 'Sorted Arrays',
    concept: 'Binary search only works because sorted arrays let us discard whole regions.',
    prompt: 'Run a comparison on the middle of this sorted array.',
    array: [4, 8, 12, 16, 20, 24, 28],
    target: 24,
    allowedBlocks: ['dsa_set_pointer', 'dsa_compare_index'],
    starterBlocks: ['middleCompare'],
    hints: ['The middle index is 3. Its value tells us which side can be ignored.', ...commonHints],
    goal: (_state, frames) =>
      frames.some((frame) => frame.event.kind === 'compare' && frame.event.index === 3),
    success: 'Good. The middle comparison is the decision point for sorted search.',
  },
  {
    id: 7,
    title: 'Binary Search',
    concept: 'Binary search keeps cutting the possible search area in half.',
    prompt: 'Use binary search to find the target in the sorted array.',
    array: [2, 5, 9, 14, 18, 23, 31, 40],
    target: 23,
    allowedBlocks: ['dsa_binary_search'],
    starterBlocks: ['binarySearch'],
    hints: ['Watch left, mid, and right. The target survives only on one side each round.', ...commonHints],
    goal: (state) => state.resultIndex === 5,
    success: 'Binary search found the target by eliminating half the choices each step.',
  },
  {
    id: 8,
    title: 'Linear vs Binary',
    concept: 'Different algorithms can solve the same problem with very different amounts of work.',
    prompt: 'Use binary search and compare its operation count with linear search from earlier.',
    array: [1, 3, 5, 7, 9, 11, 13, 15, 17],
    target: 15,
    allowedBlocks: ['dsa_binary_search', 'dsa_linear_search'],
    starterBlocks: ['binarySearch'],
    hints: ['Binary search should find 15 with fewer comparisons than checking one by one.', ...commonHints],
    goal: (state) => state.resultIndex === 7 && state.operationCount < 8,
    success: 'That smaller operation count is the intuition behind O(log n).',
  },
]
